name: 'PR automatically merger'
description: 'desc'
branding:
  icon: 'book-open'
  color: 'green'
inputs:
  token:
    required: true
  config:
    required: true
  checkStatus: 
    required: false
    description: 'Check all status before merge'
    default: 'true'
  comment:
    required: false
    description: 'Comment before merge'
    default: ''
  dryRun:
    required: false
    description: 'Dry run'
    default: 'false'
  intervalSeconds:
    required: false
    description: 'Seconds between the check'
    default: '0.1'
  failStep:
    required: false
    description: 'Fail the step if the PR is not found or merged'
    default: 'true'
  labels:
    required: false
    description: 'Comma seperated labes that target pull request should have'
    default: ''
  labelsStrategy:
    required: false
    description: 'Check condition on how to check the labels'
    default : 'all'
  ignoreLabels:
    required: false
    description: 'Comma seperated labes that target pull request should not have'
    default: ''
  ignoreLabelsStrategy:
    required: false
    description: 'Check condition on how to check the labels'
    default: 'all'
  repository:
    required: false
    description: 'The GitHub repository containing the issue or pr.'
    default: ${{ github.repository }}
  pullRequestNumber:
    required: false
    description: 'Number of the pull request'
    default: ${{ github.event.pull_request.number }}
  sha:
    required: false
    description: 'SHA of the pull request commit'
    default: ${{ github.event.pull_request.head.sha }}
  strategy:
    required: false
    description: 'Merge strategy'
    default: 'merge'
  timeoutSeconds:
    required: false
    description: 'Seconds to timeout'
    default: '60'
runs:
  using: 'node16'
  main: 'dist/auto-merge.js'

