name: 'PR automatically merger'
description: 'desc'
branding:
  icon: 'book-open'
  color: 'green'
inputs:
  token:
    required: true
    description: 'GitHub Token'

runs:
  using: 'node16'
  main: 'dist/auto-merge.js'
