name: Auto Merge Request

# TODO: Remove
permissions: write-all

on:
  status:
  pull_request:
    types: [opened, ready_for_review, reopened, synchronize, edited, labeled, unlabeled]
  pull_request_review:
    types: [submitted,qedited, dismissed]
  

jobs:
  auto-merge-request:
    name: Auto merge reqeust
    runs-on: ubuntu-latest
    steps:
      - name: Use PR auto merge action
        uses: lashapetriashvili/pr-automation-action@develop
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config: '.github/pr-automation-rules.yml'
          comment: 'Test Merge Commit'
          do-not-merge-labels: do-not-merge
